[project]
name = "web-scraping"
version = "14.02.2026"
description = "Projects in scraping the web"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "bs4>=0.0.2",
    "mechanicalsoup>=1.4.0",
    "requests>=2.32.5",
]
